# Generated by Django 5.2.7 on 2025-10-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estat", "0001_initial_squashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="importfromconfigtask",
            name="dry_run",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="importfromconfigtask",
            name="dry_run_report",
            field=models.FileField(
                default=None,
                editable=False,
                null=True,
                upload_to="estat_dry_run_reports/",
            ),
        ),
    ]
