# Generated by Django 5.2.7 on 2025-10-31 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estat", "0002_importfromconfigtask_dry_run_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="importconfig",
            name="multipliers",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Define multipliers to apply to specific dimensions values.",
            ),
        ),
        migrations.AddField(
            model_name="importconfig",
            name="value_decimal_places",
            field=models.PositiveIntegerField(
                blank=True,
                default=None,
                help_text="Round all values to this number of decimal places before importing",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="importconfig",
            name="value_multiplier",
            field=models.FloatField(
                default=1,
                help_text="Multiply all values by this factor before importing",
            ),
        ),
        migrations.AddField(
            model_name="importconfig",
            name="value_offset",
            field=models.FloatField(
                default=0, help_text="Add this value to all values before importing"
            ),
        ),
    ]
