# Generated by Django 5.2.9 on 2025-12-08 13:56

import digital_agenda.apps.estat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estat", "0003_importconfig_multipliers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="importconfig",
            name="conflict_formula",
            field=models.JSONField(
                blank=True,
                default=digital_agenda.apps.estat.models.default_formula,
                help_text="Formula to use when conflict resolution is set to 'Use formula'. Must define both the formula and how to extract each symbol from the dataset. Each symbol may use one or multiple dimensions values to identify the corresponding observation.",
            ),
        ),
        migrations.AlterField(
            model_name="importconfig",
            name="conflict_resolution",
            field=models.CharField(
                choices=[
                    ("RAISE_ERROR", "Raise errors on duplicate keys"),
                    ("SUM_VALUES", "Add values and merge flags"),
                    ("AVERAGE_VALUES", "Average values and merge flags"),
                    ("USE_FORMULA", "Use an advanced formula to merge values"),
                ],
                default="RAISE_ERROR",
                help_text="Importer behavior when a duplicate key is detected in the processed dataset. Can be used to merge multiple values into a single surrogate indicator.",
                max_length=60,
            ),
        ),
    ]
