# Generated by Django 4.1.7 on 2023-04-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("estat", "0005_importconfigtag_alter_importfromconfigtask_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="importfromconfigtask",
            name="errors",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
