# Generated by Django 4.2 on 2023-04-05 06:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("estat", "0006_importfromconfigtask_errors"),
        ("core", "0008_create_ci_collation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geogroup",
            name="code",
            field=models.CharField(
                db_collation="case_insensitive", max_length=60, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="importconfig",
            name="breakdown",
            field=models.CharField(db_collation="case_insensitive", max_length=60),
        ),
        migrations.AlterField(
            model_name="importconfig",
            name="code",
            field=models.CharField(db_collation="case_insensitive", max_length=60),
        ),
        migrations.AlterField(
            model_name="importconfig",
            name="country",
            field=models.CharField(
                db_collation="case_insensitive", default="geo", max_length=60
            ),
        ),
        migrations.AlterField(
            model_name="importconfig",
            name="indicator",
            field=models.CharField(db_collation="case_insensitive", max_length=60),
        ),
        migrations.AlterField(
            model_name="importconfig",
            name="period",
            field=models.CharField(
                db_collation="case_insensitive", default="time", max_length=60
            ),
        ),
        migrations.AlterField(
            model_name="importconfig",
            name="unit",
            field=models.CharField(
                db_collation="case_insensitive", default="unit", max_length=60
            ),
        ),
        migrations.AlterField(
            model_name="importconfigtag",
            name="code",
            field=models.CharField(
                db_collation="case_insensitive", max_length=60, unique=True
            ),
        ),
    ]
