# Generated by Django 4.2 on 2023-04-06 06:14

import digital_agenda.common.citext
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("estat", "0007_alter_geogroup_code_alter_importconfig_breakdown_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geogroup",
            name="code",
            field=digital_agenda.common.citext.CICharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name="importconfig",
            name="breakdown",
            field=digital_agenda.common.citext.CICharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="importconfig",
            name="code",
            field=digital_agenda.common.citext.CICharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="importconfig",
            name="country",
            field=digital_agenda.common.citext.CICharField(
                default="geo", max_length=60
            ),
        ),
        migrations.AlterField(
            model_name="importconfig",
            name="indicator",
            field=digital_agenda.common.citext.CICharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="importconfig",
            name="period",
            field=digital_agenda.common.citext.CICharField(
                default="time", max_length=60
            ),
        ),
        migrations.AlterField(
            model_name="importconfig",
            name="unit",
            field=digital_agenda.common.citext.CICharField(
                default="unit", max_length=60
            ),
        ),
        migrations.AlterField(
            model_name="importconfigtag",
            name="code",
            field=digital_agenda.common.citext.CICharField(max_length=60, unique=True),
        ),
    ]
