# Generated by Django 4.2 on 2023-04-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("estat", "0008_alter_geogroup_code_alter_importconfig_breakdown_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="importconfig",
            name="data_last_update",
            field=models.DateTimeField(
                help_text="Last data update of the local copy of the dataset as extracted from the ESTAT annotations",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="importconfig",
            name="datastructure_last_update",
            field=models.DateTimeField(
                help_text="Last structure update of the local copy of the dataset as extracted from the ESTAT annotations",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="importconfig",
            name="datastructure_last_version",
            field=models.CharField(
                help_text="Last version update of the local copy of the dataset as extracted from the ESTAT annotations",
                max_length=60,
                null=True,
            ),
        ),
    ]
