# Generated by Django 4.2 on 2023-04-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("estat", "0009_importconfig_data_last_update_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="importconfig",
            name="new_version_available",
            field=models.BooleanField(
                default=False,
                help_text="An updated version of the dataset is available in ESTAT",
            ),
        ),
    ]
