# Generated by Django 4.2 on 2023-04-26 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("estat", "0011_importconfig_remarks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importconfig",
            name="country_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Only include datapoints for countries in this group",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="estat.geogroup",
            ),
        ),
    ]
