# Generated by Django 4.2.1 on 2023-07-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("estat", "0012_alter_importconfig_country_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="importconfig",
            name="conflict_resolution",
            field=models.CharField(
                choices=[
                    ("RAISE_ERROR", "Raise errors on duplicate keys"),
                    ("SUM_VALUES", "Add values and merge flags"),
                    ("AVERAGE_VALUES", "Average values and merge flags"),
                ],
                default="RAISE_ERROR",
                help_text="Importer behavior when a duplicate key is detected in the processed dataset. Can be used to merge multiple values into a single surrogate indicator.",
                max_length=60,
            ),
        ),
    ]
