# Generated by Django 4.2.14 on 2024-08-21 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("estat", "0013_importconfig_conflict_resolution"),
    ]

    operations = [
        migrations.RenameField(
            model_name="importconfig",
            old_name="remarks",
            new_name="additional_remarks",
        ),
    ]
