# Generated by Django 4.2.14 on 2024-08-21 10:13

import digital_agenda.common.citext
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estat", "0014_rename_remarks_importconfig_additional_remarks"),
    ]

    operations = [
        migrations.AddField(
            model_name="importconfig",
            name="reference_period",
            field=digital_agenda.common.citext.CICharField(
                blank=True, max_length=60, null=True
            ),
        ),
        migrations.AddField(
            model_name="importconfig",
            name="reference_period_is_surrogate",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="importconfig",
            name="remarks",
            field=digital_agenda.common.citext.CICharField(
                blank=True, max_length=60, null=True
            ),
        ),
        migrations.AddField(
            model_name="importconfig",
            name="remarks_is_surrogate",
            field=models.BooleanField(default=False),
        ),
    ]
