# Generated by Django 4.2.15 on 2024-09-04 05:59

import digital_agenda.common.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("estat", "0015_importconfig_reference_period_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importconfig",
            name="reference_period",
            field=digital_agenda.common.citext.CICharField(
                blank=True,
                help_text="String only field, doesn't required related object to exist",
                max_length=60,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="importconfig",
            name="remarks",
            field=digital_agenda.common.citext.CICharField(
                blank=True,
                help_text="String only field, doesn't required related object to exist",
                max_length=60,
                null=True,
            ),
        ),
    ]
