# Generated by Django 4.2.24 on 2025-09-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estat", "0016_alter_importconfig_reference_period_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="importconfig",
            name="disable_check_updates",
            field=models.BooleanField(
                default=False,
                help_text="Don't check for new data in ESTAT",
            ),
        ),
    ]
