services:
  app:
    build:
      context: .
      dockerfile: docker/app.docker
    environment:
      - GUNICORN_CMD_ARGS=--workers=4 --threads=4

  worker:
    build:
      context: .
      dockerfile: docker/app.docker

  nginx:
    build:
      context: .
      dockerfile: docker/nginx.docker
    environment:
      - NGINX_WORKER_PROCESSES=4
    ports:
      - 8080:80