# Generated by Django 5.2.7 on 2025-10-15 06:58

import digital_agenda.common.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_breakdown_definition_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="breakdown",
            name="definition",
            field=digital_agenda.common.models.CleanCKEditor5Field(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="breakdowngroup",
            name="definition",
            field=digital_agenda.common.models.CleanCKEditor5Field(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="definition",
            field=digital_agenda.common.models.CleanCKEditor5Field(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="datasource",
            name="definition",
            field=digital_agenda.common.models.CleanCKEditor5Field(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="datasource",
            name="note",
            field=digital_agenda.common.models.CleanCKEditor5Field(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="indicator",
            name="definition",
            field=digital_agenda.common.models.CleanCKEditor5Field(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="indicator",
            name="note",
            field=digital_agenda.common.models.CleanCKEditor5Field(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="indicatorgroup",
            name="definition",
            field=digital_agenda.common.models.CleanCKEditor5Field(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="period",
            name="definition",
            field=digital_agenda.common.models.CleanCKEditor5Field(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="staticpage",
            name="body",
            field=digital_agenda.common.models.CleanCKEditor5Field(),
        ),
        migrations.AlterField(
            model_name="unit",
            name="definition",
            field=digital_agenda.common.models.CleanCKEditor5Field(
                blank=True, null=True
            ),
        ),
    ]
