# Generated by Django 4.1.4 on 2023-01-30 09:52

from django.db import migrations, models
import django.db.models.deletion


def forwards_func(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Indicator = apps.get_model("core", "Indicator")
    IndicatorDataSourceLink = apps.get_model("core", "IndicatorDataSourceLink")

    links = []
    for indicator in Indicator.objects.using(db_alias).exclude(
        data_source__isnull=True
    ):
        links.append(
            IndicatorDataSourceLink(
                indicator=indicator, data_source=indicator.data_source
            )
        )

    IndicatorDataSourceLink.objects.using(db_alias).bulk_create(links)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndicatorDataSourceLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.datasource",
                    ),
                ),
                (
                    "indicator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.indicator"
                    ),
                ),
            ],
            options={
                "unique_together": {("indicator", "data_source")},
            },
        ),
        migrations.AddField(
            model_name="indicator",
            name="data_sources",
            field=models.ManyToManyField(
                blank=True,
                related_name="indicators",
                through="core.IndicatorDataSourceLink",
                to="core.datasource",
            ),
        ),
        migrations.RunPython(forwards_func, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="indicator",
            name="data_source",
        ),
    ]
