# Generated by Django 4.1.4 on 2023-02-06 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("estat", "0002_initial"),
        ("core", "0003_remove_indicator_data_source_indicatordatasourcelink_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fact",
            name="import_config",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="facts",
                to="estat.importconfig",
            ),
        ),
    ]
