# Generated by Django 5.2.12 on 2026-04-06 08:44

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_breakdown_definition_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicatorgroup",
            name="color",
            field=colorfield.fields.ColorField(
                blank=True, default="", image_field=None, max_length=25, samples=None
            ),
        ),
        migrations.AddField(
            model_name="indicatorgroup",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="core.indicatorgroup",
            ),
        ),
        migrations.CreateModel(
            name="CountryProfileIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(db_index=True, default=100000),
                ),
                ("is_dd_kpi", models.BooleanField(default=False)),
                ("is_percentage", models.BooleanField(default=False)),
                (
                    "breakdown",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.breakdown"
                    ),
                ),
                (
                    "indicator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.indicator"
                    ),
                ),
                (
                    "indicator_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.indicatorgroup",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.period"
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.unit"
                    ),
                ),
            ],
            options={
                "ordering": ("display_order",),
                "unique_together": {("period", "indicator")},
            },
        ),
    ]
