# Generated by Django 4.1.3 on 2022-11-28 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="period",
            options={"ordering": ["-code"]},
        ),
    ]
