# Generated by Django 4.1.3 on 2022-11-28 08:39

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_period_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="color",
            field=colorfield.fields.ColorField(
                default="#CCCCCC",
                help_text="Color used for this countries chart series",
                image_field=None,
                max_length=18,
                samples=None,
            ),
        ),
    ]
