# Generated by Django 5.2.12 on 2026-04-09 05:00

import colorfield.fields
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_indicatorgroup_color_indicatorgroup_icon_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="countryprofileindicator",
            old_name="is_percentage",
            new_name="is_in_chart",
        ),
        migrations.AlterUniqueTogether(
            name="countryprofileindicator",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="indicatorgroup",
            name="color",
        ),
        migrations.AddField(
            model_name="countryprofileindicator",
            name="limit_to_periods",
            field=models.ManyToManyField(
                blank=True,
                help_text="Show indicator in country profile only for these periods",
                related_name="+",
                to="core.period",
            ),
        ),
        migrations.AddField(
            model_name="countryprofileindicator",
            name="target_breakdown",
            field=models.ForeignKey(
                blank=True,
                help_text="Show EU target for this indicator using this breakdown",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core.breakdown",
            ),
        ),
        migrations.AddField(
            model_name="indicatorgroup",
            name="colors",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=colorfield.fields.ColorField(
                    blank=True,
                    default="",
                    image_field=None,
                    max_length=25,
                    samples=None,
                ),
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="countryprofileindicator",
            name="breakdown",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core.breakdown",
            ),
        ),
        migrations.AlterField(
            model_name="countryprofileindicator",
            name="indicator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core.indicator",
            ),
        ),
        migrations.AlterField(
            model_name="countryprofileindicator",
            name="indicator_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core.indicatorgroup",
            ),
        ),
        migrations.AlterField(
            model_name="countryprofileindicator",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core.unit",
            ),
        ),
        migrations.AddConstraint(
            model_name="countryprofileindicator",
            constraint=models.UniqueConstraint(
                fields=("indicator",), name="country_profile_indicator_unique_indicator"
            ),
        ),
        migrations.RemoveField(
            model_name="countryprofileindicator",
            name="period",
        ),
    ]
