# Generated by Django 5.2.14 on 2026-05-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "core",
            "0005_rename_is_percentage_countryprofileindicator_is_in_chart_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="countryprofileindicator",
            name="indicator_alias",
            field=models.TextField(blank=True),
        ),
    ]
