# Generated by Django 5.2.14 on 2026-05-25 12:09

import django.db.models.deletion
from django.db import migrations, models

import digital_agenda.common.models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_countryprofileindicator_indicator_alias"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndicatorMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "description",
                    digital_agenda.common.models.CleanCKEditor5Field(blank=True),
                ),
                (
                    "breakdown",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.breakdown",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.country",
                    ),
                ),
                (
                    "indicator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata",
                        to="core.indicator",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.period",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.unit",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
