# Generated by Django 5.2.14 on 2026-05-28 04:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_indicatormetadata"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="indicatormetadata",
            options={"ordering": ["display_order"]},
        ),
        migrations.AddField(
            model_name="indicatormetadata",
            name="display_order",
            field=models.PositiveIntegerField(db_index=True, default=100000),
        ),
    ]
