# Generated by Django 4.1.4 on 2023-01-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_fact_import_config"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="indicator",
            name="breakdowns",
        ),
        migrations.RemoveField(
            model_name="indicator",
            name="countries",
        ),
        migrations.RemoveField(
            model_name="indicator",
            name="periods",
        ),
        migrations.RemoveField(
            model_name="indicator",
            name="units",
        ),
        migrations.AlterField(
            model_name="period",
            name="code",
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
