# Generated by Django 4.2 on 2023-04-06 06:14

import digital_agenda.common.citext
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_alter_breakdown_code_alter_breakdowngroup_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="breakdown",
            name="code",
            field=digital_agenda.common.citext.CICharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name="breakdowngroup",
            name="code",
            field=digital_agenda.common.citext.CICharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="code",
            field=digital_agenda.common.citext.CICharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name="datasource",
            name="code",
            field=digital_agenda.common.citext.CICharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name="indicator",
            name="code",
            field=digital_agenda.common.citext.CICharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name="indicatorgroup",
            name="code",
            field=digital_agenda.common.citext.CICharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="code",
            field=digital_agenda.common.citext.CICharField(max_length=60, unique=True),
        ),
    ]
