# Generated by Django 4.2.1 on 2023-05-22 06:12
from datetime import date
from datetime import timedelta

import digital_agenda.common.citext
from django.db import migrations, models


def forwards_func(apps, schema_editor):
    Period = apps.get_model("core", "Period")
    db_alias = schema_editor.connection.alias

    for period in Period.objects.using(db_alias).all():
        date_start = date(int(period.code), 1, 1)
        date_end = date(int(period.code), 12, 31)
        mid_date = date_start + timedelta(days=round((date_end - date_start).days / 2))

        period.date = mid_date
        period.label = f"Year: {period.code}"
        period.alt_label = period.code
        period.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_alter_breakdown_code_alter_breakdowngroup_code_and_more")
    ]

    operations = [
        migrations.AddField(
            model_name="period", name="date", field=models.DateField(null=True)
        ),
        migrations.AlterField(
            model_name="period",
            name="code",
            field=digital_agenda.common.citext.CICharField(max_length=60, unique=True),
        ),
        migrations.RunPython(forwards_func, reverse_code=migrations.RunPython.noop),
    ]
