# Generated by Django 4.2.1 on 2023-05-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_period_date_alter_period_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="period",
            name="date",
            field=models.DateField(blank=True, db_index=True),
        ),
    ]
