# Generated by Django 4.2.3 on 2023-09-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_alter_period_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicator",
            name="time_coverage",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Time coverage to display instead of the automatically calculated one",
                max_length=255,
                null=True,
            ),
        ),
    ]
