# Generated by Django 4.2.10 on 2024-02-16 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_country_color"),
    ]

    operations = []
