# Generated by Django 4.2.14 on 2024-08-21 10:13

import digital_agenda.common.citext
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_alter_breakdown_definition_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fact",
            name="reference_period",
            field=digital_agenda.common.citext.CICharField(
                blank=True, max_length=60, null=True
            ),
        ),
        migrations.AddField(
            model_name="fact",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
    ]
