# Generated by Django 4.2.16 on 2024-11-15 07:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_fact_reference_period_fact_remarks"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaticPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=255, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("body", ckeditor.fields.RichTextField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
