# Generated by Django 4.2.14 on 2024-08-21 10:29

from django.db import migrations


def forwards_func(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Fact = apps.get_model("core", "Fact")
    ExtraChartNote = apps.get_model("charts", "ExtraChartNote")

    for obj in ExtraChartNote.objects.using(db_alias).all():
        reference_period = int(obj.note.strip()[-5:-1])
        assert reference_period > 2000

        Fact.objects.using(db_alias).filter(
            indicator=obj.indicator, period=obj.period
        ).update(reference_period=str(reference_period))


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_fact_reference_period_fact_remarks"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_code=migrations.RunPython.noop),
    ]
