# Generated by Django 4.0.4 on 2022-05-17 08:39

from django.db import migrations


def add_datasource(apps, schema_editor):
    DataSource = apps.get_model("core", "DataSource")  # noqa
    DataSource.objects.update_or_create(name="ESTAT")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_initial"),
    ]

    operations = [migrations.RunPython(add_datasource)]
