# Generated by Django 4.2 on 2023-04-05 06:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_email"),
        ("core", "0008_create_ci_collation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                db_collation="case_insensitive", max_length=254, unique=True
            ),
        ),
    ]
