# Generated by Django 4.2 on 2023-04-06 06:14

import digital_agenda.common.citext
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=digital_agenda.common.citext.CIEmailField(
                max_length=254, unique=True
            ),
        ),
    ]
