version: '3.8'

services:

  db:
    image: postgres:14.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - "${DOCKER_ENV_FILE}"
    expose:
      - 5432

  broker:
    image: rabbitmq:3.10.5-management
    env_file:
      - "${DOCKER_ENV_FILE}"

  app-http:
    image: digital-agenda-app
    volumes:
      - static_files:/static
      - bulk_downloads:/bulk
      - media:/media
    expose:
      - "8001"
    env_file:
      - "${DOCKER_ENV_FILE}"
    depends_on:
      - db
      - broker

  app-worker:
    image: digital-agenda-app
    volumes:
      - bulk_downloads:/bulk
      - media:/media
    command: ["/venv/bin/celery", "-A", "digital_agenda", "worker", "-l", "info", "-n", "digital_agenda@h", "--concurrency=1"]
    env_file:
      - "${DOCKER_ENV_FILE}"
    depends_on:
      - db
      - broker

  app-ws:
    image: digital-agenda-app
    volumes:
      - bulk_downloads:/bulk
      - media:/media
    command: ["/venv/bin/daphne", "digital_agenda.site.asgi:application", "-b", "0.0.0.0", "-p", "8002"]
    env_file:
      - "${DOCKER_ENV_FILE}"
    depends_on:
      - db
      - broker

  nginx:
    image: digital-agenda-nginx
    volumes:
      - static_files:/static
      - media:/media
    ports:
      - "8000:8000"
    depends_on:
      - app-http
      - app-ws

volumes:
  postgres_data:
  static_files:
  bulk_downloads:
  media:
