# Generated by Django 4.0.4 on 2022-05-16 07:38

import django.contrib.postgres.fields.citext
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("estat", "0001_citext"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=300, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "code",
                    django.contrib.postgres.fields.citext.CICharField(
                        max_length=60, unique=True
                    ),
                ),
            ],
            options={
                "db_table": "estat_datasets",
            },
        ),
        migrations.CreateModel(
            name="Dimension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=300, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "code",
                    django.contrib.postgres.fields.citext.CICharField(max_length=60),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dimensions",
                        to="estat.dataset",
                    ),
                ),
            ],
            options={
                "db_table": "estat_dimensions",
            },
        ),
        migrations.CreateModel(
            name="DimensionValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=300, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "code",
                    django.contrib.postgres.fields.citext.CICharField(max_length=60),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "dimension",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="estat.dimension",
                    ),
                ),
            ],
            options={
                "db_table": "estat_dim_values",
            },
        ),
        migrations.CreateModel(
            name="DatasetConfig",
            fields=[
                (
                    "dataset",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="config",
                        serialize=False,
                        to="estat.dataset",
                    ),
                ),
            ],
            options={
                "db_table": "estat_dataset_configs",
            },
        ),
        migrations.CreateModel(
            name="Fact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField(blank=True, null=True)),
                ("flags", models.CharField(blank=True, max_length=2)),
                (
                    "breakdown",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="estat.dimensionvalue",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="estat.dimensionvalue",
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facts",
                        to="estat.dataset",
                    ),
                ),
                (
                    "indicator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="estat.dimensionvalue",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="estat.dimensionvalue",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="estat.dimensionvalue",
                    ),
                ),
            ],
            options={
                "db_table": "estat_facts",
            },
        ),
        migrations.AddConstraint(
            model_name="fact",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("value__isnull", False),
                    models.Q(("flags", ""), _negated=True),
                    _connector="OR",
                ),
                name="estat_fact_either_val_or_flags",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="fact",
            unique_together={
                ("dataset", "indicator", "breakdown", "unit", "country", "period")
            },
        ),
        migrations.AlterUniqueTogether(
            name="dimensionvalue",
            unique_together={("dimension", "code")},
        ),
        migrations.AddField(
            model_name="datasetconfig",
            name="breakdown",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="estat.dimension",
            ),
        ),
        migrations.AddField(
            model_name="datasetconfig",
            name="breakdown_surrogate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="estat.dimensionvalue",
            ),
        ),
        migrations.AddField(
            model_name="datasetconfig",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="estat.dimension",
            ),
        ),
        migrations.AddField(
            model_name="datasetconfig",
            name="country_surrogate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="estat.dimensionvalue",
            ),
        ),
        migrations.AddField(
            model_name="datasetconfig",
            name="indicator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="estat.dimension",
            ),
        ),
        migrations.AddField(
            model_name="datasetconfig",
            name="indicator_surrogate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="estat.dimensionvalue",
            ),
        ),
        migrations.AddField(
            model_name="datasetconfig",
            name="period",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="estat.dimension",
            ),
        ),
        migrations.AddField(
            model_name="datasetconfig",
            name="period_surrogate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="estat.dimensionvalue",
            ),
        ),
        migrations.AddField(
            model_name="datasetconfig",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="estat.dimension",
            ),
        ),
        migrations.AddField(
            model_name="datasetconfig",
            name="unit_surrogate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="estat.dimensionvalue",
            ),
        ),
    ]
