# Generated by Django 5.2.7 on 2025-10-07 07:43

import django.db.models.deletion
import hashid_field.field
from django.contrib.postgres.operations import CITextExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("charts", "0001_initial_squashed"),
    ]

    operations = [
        CITextExtension(),
        migrations.CreateModel(
            name="ShortURL",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    hashid_field.field.BigHashidAutoField(
                        alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",
                        min_length=13,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "query_arguments",
                    models.CharField(blank=True, default="", max_length=1024),
                ),
                (
                    "chart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="charts.chart"
                    ),
                ),
            ],
            options={
                "unique_together": {("chart", "query_arguments")},
            },
        ),
    ]
