# Generated by Django 4.1.3 on 2022-11-17 08:10

import ckeditor.fields
import django.contrib.postgres.fields.citext
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChartGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "display_order",
                    models.PositiveIntegerField(db_index=True, default=100000),
                ),
                (
                    "is_draft",
                    models.BooleanField(
                        default=False,
                        help_text="Draft items will only be visible for admins.",
                    ),
                ),
                (
                    "code",
                    django.contrib.postgres.fields.citext.CICharField(
                        max_length=60, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("short_name", models.CharField(max_length=40)),
                ("description", ckeditor.fields.RichTextField()),
                ("image", models.ImageField(blank=True, upload_to="")),
            ],
            options={
                "db_table": "chart_groups",
                "ordering": ["display_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="ChartGroupIndicatorLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(db_index=True, default=100000),
                ),
                (
                    "chart_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="charts.chartgroup",
                    ),
                ),
                (
                    "indicator_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.indicatorgroup",
                    ),
                ),
            ],
            options={
                "db_table": "chart_group_links",
                "ordering": ["display_order"],
                "unique_together": {("indicator_group", "chart_group")},
            },
        ),
        migrations.AddField(
            model_name="chartgroup",
            name="indicator_groups",
            field=models.ManyToManyField(
                through="charts.ChartGroupIndicatorLink", to="core.indicatorgroup"
            ),
        ),
        migrations.AddField(
            model_name="chartgroup",
            name="periods",
            field=models.ManyToManyField(
                blank=True,
                db_table="chart_group_periods",
                help_text="Limit chart group to the specified periods. If none are specified ALL available periods are used instead.",
                to="core.period",
            ),
        ),
    ]
