# Generated by Django 4.1.3 on 2022-12-17 08:48

import ckeditor.fields
import django.contrib.postgres.fields.citext
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0006_country_is_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChartGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "display_order",
                    models.PositiveIntegerField(db_index=True, default=100000),
                ),
                (
                    "is_draft",
                    models.BooleanField(
                        default=False,
                        help_text="Draft items will only be visible for admins.",
                    ),
                ),
                (
                    "code",
                    django.contrib.postgres.fields.citext.CICharField(
                        max_length=60, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("short_name", models.CharField(max_length=40)),
                ("description", ckeditor.fields.RichTextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Thumbnail image for this Chart Group. A placeholder will be used if this is not configured.",
                        upload_to="",
                    ),
                ),
                (
                    "indicator_group_label",
                    models.CharField(default="Indicator group", max_length=60),
                ),
                (
                    "indicator_label",
                    models.CharField(default="Indicator", max_length=60),
                ),
                (
                    "breakdown_group_label",
                    models.CharField(default="Breakdown group", max_length=60),
                ),
                (
                    "breakdown_label",
                    models.CharField(default="Breakdown", max_length=60),
                ),
                ("period_label", models.CharField(default="Period", max_length=60)),
                (
                    "unit_label",
                    models.CharField(default="Unit of measure", max_length=60),
                ),
                ("indicator_groups", models.ManyToManyField(to="core.indicatorgroup")),
                (
                    "periods",
                    models.ManyToManyField(
                        blank=True,
                        db_table="chart_group_periods",
                        help_text="Limit chart group to the specified periods. If none are specified ALL available periods are used instead.",
                        to="core.period",
                    ),
                ),
            ],
            options={
                "db_table": "chart_groups",
                "ordering": ["display_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="Chart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "display_order",
                    models.PositiveIntegerField(db_index=True, default=100000),
                ),
                (
                    "is_draft",
                    models.BooleanField(
                        default=False,
                        help_text="Draft items will only be visible for admins.",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.SlugField(unique=True)),
                (
                    "chart_type",
                    models.CharField(
                        choices=[
                            (
                                "Column",
                                (
                                    (
                                        "COLUMN_COMPARE_COUNTRIES",
                                        "Column Chart: Compare Countries",
                                    ),
                                    (
                                        "COLUMN_COMPARE_BREAKDOWNS",
                                        "Column Chart: Compare Breakdowns",
                                    ),
                                    (
                                        "COLUMN_STACKED_COMPARE_BREAKDOWNS",
                                        "Column Chart Stacked: Compare Breakdowns",
                                    ),
                                    (
                                        "COLUMN_STACKED_COMPARE_BREAKDOWNS_WEIGHTED",
                                        "Column Chart Stacked: Compare Breakdowns Weighted",
                                    ),
                                ),
                            ),
                            (
                                "Spline",
                                (
                                    (
                                        "SPLINE_COMPARE_COUNTRIES",
                                        "Spline Chart: Compare Countries",
                                    ),
                                    (
                                        "SPLINE_COMPARE_BREAKDOWNS",
                                        "Spline Chart: Compare Breakdowns",
                                    ),
                                    (
                                        "SPLINE_COMPARE_TWO_INDICATORS",
                                        "Spline Chart: Compare Two Indicators",
                                    ),
                                ),
                            ),
                            (
                                "Scatter",
                                (
                                    (
                                        "SCATTER_COMPARE_TWO_INDICATORS",
                                        "Scatter Chart: Compare Two Indicators",
                                    ),
                                ),
                            ),
                            (
                                "Bubble",
                                (
                                    (
                                        "BUBBLE_COMPARE_THREE_INDICATORS",
                                        "Bubble Chart: Compare Three Indicators",
                                    ),
                                ),
                            ),
                            (
                                "Map",
                                (
                                    (
                                        "MAP_COMPARE_COUNTRIES",
                                        "Map Chart: Compare Countries",
                                    ),
                                ),
                            ),
                            ("Table", (("TABLE_DEBUG_DATA", "Table: Debug Data"),)),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", ckeditor.fields.RichTextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Custom thumbnail image to use for this chart. If not set, a default one will be used depending on the chart type.",
                        upload_to="",
                    ),
                ),
                (
                    "indicator_group_filter_hidden",
                    models.BooleanField(
                        default=False, help_text="Force hide the filter for this chart."
                    ),
                ),
                (
                    "indicator_filter_hidden",
                    models.BooleanField(
                        default=False, help_text="Force hide the filter for this chart."
                    ),
                ),
                (
                    "breakdown_group_filter_hidden",
                    models.BooleanField(
                        default=False, help_text="Force hide the filter for this chart."
                    ),
                ),
                (
                    "breakdown_filter_hidden",
                    models.BooleanField(
                        default=False, help_text="Force hide the filter for this chart."
                    ),
                ),
                (
                    "period_filter_hidden",
                    models.BooleanField(
                        default=False, help_text="Force hide the filter for this chart."
                    ),
                ),
                (
                    "unit_filter_hidden",
                    models.BooleanField(
                        default=False, help_text="Force hide the filter for this chart."
                    ),
                ),
                (
                    "country_filter_hidden",
                    models.BooleanField(
                        default=False, help_text="Force hide the filter for this chart."
                    ),
                ),
                (
                    "breakdown_filter_defaults",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Multiple defaults can be specified, however only valid choices depending on the other filters will be used.",
                        related_name="default_charts",
                        to="core.breakdown",
                    ),
                ),
                (
                    "breakdown_filter_ignored",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Values specified here will be hidden and not available for selection.",
                        related_name="ignored_charts",
                        to="core.breakdown",
                    ),
                ),
                (
                    "breakdown_group_filter_defaults",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Multiple defaults can be specified, however only valid choices depending on the other filters will be used.",
                        related_name="default_charts",
                        to="core.breakdowngroup",
                    ),
                ),
                (
                    "breakdown_group_filter_ignored",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Values specified here will be hidden and not available for selection.",
                        related_name="ignored_charts",
                        to="core.breakdowngroup",
                    ),
                ),
                (
                    "chart_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="charts.chartgroup",
                    ),
                ),
                (
                    "country_filter_defaults",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Multiple defaults can be specified, however only valid choices depending on the other filters will be used.",
                        related_name="default_charts",
                        to="core.country",
                    ),
                ),
                (
                    "country_filter_ignored",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Values specified here will be hidden and not available for selection.",
                        related_name="ignored_charts",
                        to="core.country",
                    ),
                ),
                (
                    "indicator_filter_defaults",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Multiple defaults can be specified, however only valid choices depending on the other filters will be used.",
                        related_name="default_charts",
                        to="core.indicator",
                    ),
                ),
                (
                    "indicator_filter_ignored",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Values specified here will be hidden and not available for selection.",
                        related_name="ignored_charts",
                        to="core.indicator",
                    ),
                ),
                (
                    "indicator_group_filter_defaults",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Multiple defaults can be specified, however only valid choices depending on the other filters will be used.",
                        related_name="default_charts",
                        to="core.indicatorgroup",
                    ),
                ),
                (
                    "indicator_group_filter_ignored",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Values specified here will be hidden and not available for selection.",
                        related_name="ignored_charts",
                        to="core.indicatorgroup",
                    ),
                ),
                (
                    "period_filter_defaults",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Multiple defaults can be specified, however only valid choices depending on the other filters will be used.",
                        related_name="default_charts",
                        to="core.period",
                    ),
                ),
                (
                    "period_filter_ignored",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Values specified here will be hidden and not available for selection.",
                        related_name="ignored_charts",
                        to="core.period",
                    ),
                ),
                (
                    "unit_filter_defaults",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Multiple defaults can be specified, however only valid choices depending on the other filters will be used.",
                        related_name="default_charts",
                        to="core.unit",
                    ),
                ),
                (
                    "unit_filter_ignored",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Values specified here will be hidden and not available for selection.",
                        related_name="ignored_charts",
                        to="core.unit",
                    ),
                ),
            ],
            options={
                "db_table": "charts",
                "ordering": ["display_order", "code"],
            },
        ),
    ]
