# Generated by Django 5.2.7 on 2025-10-14 05:21

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("charts", "0001_initial_squashed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chart",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name="chartgroup",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name="chartgroup",
            name="license",
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
