# Generated by Django 5.2.7 on 2025-10-15 06:58

import digital_agenda.common.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "charts",
            "0002_alter_chart_description_alter_chartgroup_description_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="chart",
            name="description",
            field=digital_agenda.common.models.CleanCKEditor5Field(),
        ),
        migrations.AlterField(
            model_name="chartgroup",
            name="description",
            field=digital_agenda.common.models.CleanCKEditor5Field(),
        ),
        migrations.AlterField(
            model_name="chartgroup",
            name="license",
            field=digital_agenda.common.models.CleanCKEditor5Field(),
        ),
    ]
