# Generated by Django 4.1.4 on 2023-01-30 06:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charts", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chartgroup",
            name="periods",
        ),
        migrations.AddField(
            model_name="chartgroup",
            name="period_end",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Limit chart group to the specific periods less than or equal to this year",
                null=True,
                validators=[django.core.validators.MinValueValidator(1990)],
            ),
        ),
        migrations.AddField(
            model_name="chartgroup",
            name="period_start",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Limit chart group to the specific periods greater than or equal to this year",
                null=True,
                validators=[django.core.validators.MinValueValidator(1990)],
            ),
        ),
    ]
