# Generated by Django 5.2.7 on 2025-11-10 13:37

from django.db import migrations, models


def migrate_country_multi(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Chart = apps.get_model("charts", "Chart")

    Chart.objects.using(db_alias).filter(
        chart_type__in=(
            "SPLINE_COMPARE_BREAKDOWNS",
            "SPLINE_COMPARE_TWO_INDICATORS",
        )
    ).update(country_multi_filter=False)


class Migration(migrations.Migration):

    dependencies = [
        (
            "charts",
            "0003_alter_chart_description_alter_chartgroup_description_and_more",
        ),
        ("core", "0003_alter_breakdown_definition_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chart",
            name="breakdown_filter_values",
            field=models.ManyToManyField(
                blank=True,
                help_text="If specified, only values specified here will be available for selection.",
                related_name="restricted_charts",
                to="core.breakdown",
            ),
        ),
        migrations.AddField(
            model_name="chart",
            name="breakdown_group_filter_values",
            field=models.ManyToManyField(
                blank=True,
                help_text="If specified, only values specified here will be available for selection.",
                related_name="restricted_charts",
                to="core.breakdowngroup",
            ),
        ),
        migrations.AddField(
            model_name="chart",
            name="country_filter_values",
            field=models.ManyToManyField(
                blank=True,
                help_text="If specified, only values specified here will be available for selection.",
                related_name="restricted_charts",
                to="core.country",
            ),
        ),
        migrations.AddField(
            model_name="chart",
            name="country_multi_filter",
            field=models.BooleanField(
                default=True,
                help_text="Allow multiple countries to be selected for this chart.",
            ),
        ),
        migrations.AddField(
            model_name="chart",
            name="indicator_filter_values",
            field=models.ManyToManyField(
                blank=True,
                help_text="If specified, only values specified here will be available for selection.",
                related_name="restricted_charts",
                to="core.indicator",
            ),
        ),
        migrations.AddField(
            model_name="chart",
            name="indicator_group_filter_values",
            field=models.ManyToManyField(
                blank=True,
                help_text="If specified, only values specified here will be available for selection.",
                related_name="restricted_charts",
                to="core.indicatorgroup",
            ),
        ),
        migrations.AddField(
            model_name="chart",
            name="period_filter_values",
            field=models.ManyToManyField(
                blank=True,
                help_text="If specified, only values specified here will be available for selection.",
                related_name="restricted_charts",
                to="core.period",
            ),
        ),
        migrations.AddField(
            model_name="chart",
            name="unit_filter_values",
            field=models.ManyToManyField(
                blank=True,
                help_text="If specified, only values specified here will be available for selection.",
                related_name="restricted_charts",
                to="core.unit",
            ),
        ),
        migrations.RunPython(
            migrate_country_multi, reverse_code=migrations.RunPython.noop
        ),
    ]
