# Generated by Django 4.1.6 on 2023-02-08 06:39

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("charts", "0003_remove_chartgroup_periods_chartgroup_period_end_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chartgroup",
            name="license",
            field=models.TextField(
                default="http://ec.europa.eu/geninfo/legal_notices_en.htm#copyright"
            ),
            preserve_default=False,
        ),
    ]
