# Generated by Django 4.1.7 on 2023-02-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("charts", "0004_chartgroup_license"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chart",
            name="chart_type",
            field=models.CharField(
                choices=[
                    (
                        "Column",
                        (
                            (
                                "COLUMN_COMPARE_COUNTRIES",
                                "Column Chart: Compare Countries",
                            ),
                            (
                                "COLUMN_COMPARE_BREAKDOWNS",
                                "Column Chart: Compare Breakdowns",
                            ),
                            (
                                "COLUMN_STACKED_COMPARE_BREAKDOWNS",
                                "Column Chart Stacked: Compare Breakdowns",
                            ),
                            (
                                "COLUMN_STACKED_COMPARE_BREAKDOWNS_WEIGHTED",
                                "Column Chart Stacked: Compare Breakdowns Weighted",
                            ),
                        ),
                    ),
                    (
                        "Bar",
                        (
                            ("BAR_COMPARE_COUNTRIES", "Bar Chart: Compare Countries"),
                            ("BAR_COMPARE_BREAKDOWNS", "Bar Chart: Compare Breakdowns"),
                            (
                                "BAR_STACKED_COMPARE_BREAKDOWNS",
                                "Bar Chart Stacked: Compare Breakdowns",
                            ),
                            (
                                "BAR_STACKED_COMPARE_BREAKDOWNS_WEIGHTED",
                                "Bar Chart Stacked: Compare Breakdowns Weighted",
                            ),
                        ),
                    ),
                    (
                        "Spline",
                        (
                            (
                                "SPLINE_COMPARE_COUNTRIES",
                                "Spline Chart: Compare Countries",
                            ),
                            (
                                "SPLINE_COMPARE_BREAKDOWNS",
                                "Spline Chart: Compare Breakdowns",
                            ),
                            (
                                "SPLINE_COMPARE_TWO_INDICATORS",
                                "Spline Chart: Compare Two Indicators",
                            ),
                        ),
                    ),
                    (
                        "Scatter",
                        (
                            (
                                "SCATTER_COMPARE_TWO_INDICATORS",
                                "Scatter Chart: Compare Two Indicators",
                            ),
                        ),
                    ),
                    (
                        "Bubble",
                        (
                            (
                                "BUBBLE_COMPARE_THREE_INDICATORS",
                                "Bubble Chart: Compare Three Indicators",
                            ),
                        ),
                    ),
                    (
                        "Map",
                        (("MAP_COMPARE_COUNTRIES", "Map Chart: Compare Countries"),),
                    ),
                    ("Table", (("TABLE_DEBUG_DATA", "Table: Debug Data"),)),
                ],
                max_length=50,
            ),
        ),
    ]
