# Generated by Django 4.1.7 on 2023-03-08 10:06

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    Chart = apps.get_model("charts", "chart")
    db_alias = schema_editor.connection.alias

    Chart.objects.using(db_alias).filter(chart_type="MAP_COMPARE_COUNTRIES").update(
        chart_type="MAP_EU_COMPARE_COUNTRIES"
    )


def reverse_func(apps, schema_editor):
    Chart = apps.get_model("charts", "chart")
    db_alias = schema_editor.connection.alias

    Chart.objects.using(db_alias).filter(chart_type="MAP_EU_COMPARE_COUNTRIES").update(
        chart_type="MAP_COMPARE_COUNTRIES"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("charts", "0005_alter_chart_chart_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chart",
            name="chart_type",
            field=models.CharField(
                choices=[
                    (
                        "Column",
                        (
                            (
                                "COLUMN_COMPARE_COUNTRIES",
                                "Column Chart: Compare Countries",
                            ),
                            (
                                "COLUMN_COMPARE_BREAKDOWNS",
                                "Column Chart: Compare Breakdowns",
                            ),
                            (
                                "COLUMN_STACKED_COMPARE_BREAKDOWNS",
                                "Column Chart Stacked: Compare Breakdowns",
                            ),
                            (
                                "COLUMN_STACKED_COMPARE_BREAKDOWNS_WEIGHTED",
                                "Column Chart Stacked: Compare Breakdowns Weighted",
                            ),
                        ),
                    ),
                    (
                        "Bar",
                        (
                            ("BAR_COMPARE_COUNTRIES", "Bar Chart: Compare Countries"),
                            ("BAR_COMPARE_BREAKDOWNS", "Bar Chart: Compare Breakdowns"),
                            (
                                "BAR_STACKED_COMPARE_BREAKDOWNS",
                                "Bar Chart Stacked: Compare Breakdowns",
                            ),
                            (
                                "BAR_STACKED_COMPARE_BREAKDOWNS_WEIGHTED",
                                "Bar Chart Stacked: Compare Breakdowns Weighted",
                            ),
                        ),
                    ),
                    (
                        "Spline",
                        (
                            (
                                "SPLINE_COMPARE_COUNTRIES",
                                "Spline Chart: Compare Countries",
                            ),
                            (
                                "SPLINE_COMPARE_BREAKDOWNS",
                                "Spline Chart: Compare Breakdowns",
                            ),
                            (
                                "SPLINE_COMPARE_TWO_INDICATORS",
                                "Spline Chart: Compare Two Indicators",
                            ),
                        ),
                    ),
                    (
                        "Scatter",
                        (
                            (
                                "SCATTER_COMPARE_TWO_INDICATORS",
                                "Scatter Chart: Compare Two Indicators",
                            ),
                        ),
                    ),
                    (
                        "Bubble",
                        (
                            (
                                "BUBBLE_COMPARE_THREE_INDICATORS",
                                "Bubble Chart: Compare Three Indicators",
                            ),
                        ),
                    ),
                    (
                        "EU Map",
                        (
                            (
                                "MAP_EU_COMPARE_COUNTRIES",
                                "EU Map Chart: Compare Countries",
                            ),
                        ),
                    ),
                    (
                        "World Map",
                        (
                            (
                                "MAP_WORLD_COMPARE_COUNTRIES",
                                "World Map Chart: Compare Countries",
                            ),
                        ),
                    ),
                    ("Table", (("TABLE_DEBUG_DATA", "Table: Debug Data"),)),
                ],
                max_length=50,
            ),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
