# Generated by Django 4.1.7 on 2023-03-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("charts", "0006_alter_chart_chart_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="chart",
            name="max_value",
            field=models.FloatField(
                blank=True,
                default=None,
                help_text="Maximum value of the axis",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="chart",
            name="min_value",
            field=models.FloatField(
                blank=True,
                default=None,
                help_text="Minimum value of the axis",
                null=True,
            ),
        ),
    ]
