# Generated by Django 4.2 on 2023-04-05 06:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("charts", "0007_chart_max_value_chart_min_value"),
        ("core", "0008_create_ci_collation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chartgroup",
            name="code",
            field=models.CharField(
                db_collation="case_insensitive", max_length=60, unique=True
            ),
        ),
    ]
