# Generated by Django 4.2 on 2023-04-06 06:14

import digital_agenda.common.citext
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("charts", "0008_alter_chartgroup_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chartgroup",
            name="code",
            field=digital_agenda.common.citext.CICharField(max_length=60, unique=True),
        ),
    ]
