# Generated by Django 4.2.3 on 2023-09-18 13:56

from django.db import migrations, models
import hashid_field.field


class Migration(migrations.Migration):
    dependencies = [
        ("charts", "0009_alter_chartgroup_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chart",
            name="code",
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name="chart",
            name="id",
            field=hashid_field.field.BigHashidAutoField(
                alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",
                min_length=13,
                prefix="",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="chart",
            unique_together={("chart_group", "code")},
        ),
    ]
