# Generated by Django 4.2.3 on 2023-09-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("charts", "0010_alter_chart_code_alter_chart_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chart",
            name="code",
            field=models.SlugField(max_length=255),
        ),
    ]
