# Generated by Django 4.2.3 on 2023-09-22 10:04

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_alter_period_date"),
        ("charts", "0011_alter_chart_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndicatorChartOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "color",
                    colorfield.fields.ColorField(
                        blank=True,
                        default=None,
                        help_text="Color used for this indicator chart series",
                        image_field=None,
                        max_length=18,
                        null=True,
                        samples=None,
                    ),
                ),
                (
                    "dash_style",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Dash", "Dash"),
                            ("DashDot", "DashDot"),
                            ("Dot", "Dot"),
                            ("LongDash", "LongDash"),
                            ("LongDashDot", "LongDashDot"),
                            ("LongDashDotDot", "LongDashDotDot"),
                            ("ShortDash", "ShortDash"),
                            ("ShortDashDot", "ShortDashDot"),
                            ("ShortDashDotDot", "ShortDashDotDot"),
                            ("ShortDot", "ShortDot"),
                            ("Solid", "Solid"),
                        ],
                        default=None,
                        help_text="https://api.highcharts.com/highcharts/plotOptions.spline.dashStyle",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "symbol",
                    models.ImageField(
                        blank=True,
                        default=None,
                        help_text="https://api.highcharts.com/highcharts/plotOptions.spline.marker.symbol",
                        null=True,
                        upload_to="",
                    ),
                ),
                (
                    "indicator",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chart_options",
                        to="core.indicator",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BreakdownChartOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "color",
                    colorfield.fields.ColorField(
                        blank=True,
                        default=None,
                        help_text="Color used for this indicator chart series",
                        image_field=None,
                        max_length=18,
                        null=True,
                        samples=None,
                    ),
                ),
                (
                    "dash_style",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Dash", "Dash"),
                            ("DashDot", "DashDot"),
                            ("Dot", "Dot"),
                            ("LongDash", "LongDash"),
                            ("LongDashDot", "LongDashDot"),
                            ("LongDashDotDot", "LongDashDotDot"),
                            ("ShortDash", "ShortDash"),
                            ("ShortDashDot", "ShortDashDot"),
                            ("ShortDashDotDot", "ShortDashDotDot"),
                            ("ShortDot", "ShortDot"),
                            ("Solid", "Solid"),
                        ],
                        default=None,
                        help_text="https://api.highcharts.com/highcharts/plotOptions.spline.dashStyle",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "symbol",
                    models.ImageField(
                        blank=True,
                        default=None,
                        help_text="https://api.highcharts.com/highcharts/plotOptions.spline.marker.symbol",
                        null=True,
                        upload_to="",
                    ),
                ),
                (
                    "breakdown",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chart_options",
                        to="core.breakdown",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
