# Generated by Django 4.2.3 on 2023-09-26 11:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("charts", "0012_indicatorchartoption_breakdownchartoption"),
    ]

    operations = [
        migrations.RenameField(
            model_name="breakdownchartoption",
            old_name="symbol",
            new_name="custom_symbol",
        ),
        migrations.RenameField(
            model_name="indicatorchartoption",
            old_name="symbol",
            new_name="custom_symbol",
        ),
    ]
