# Generated by Django 4.2.3 on 2023-09-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("charts", "0013_rename_symbol_breakdownchartoption_custom_symbol_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="breakdownchartoption",
            name="symbol",
            field=models.CharField(
                blank=True,
                choices=[
                    ("circle", "circle"),
                    ("square", "square"),
                    ("diamond", "diamond"),
                    ("triangle", "triangle"),
                    ("triangle-down", "triangle-down"),
                ],
                default=None,
                help_text="https://api.highcharts.com/highcharts/plotOptions.spline.marker.symbol",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="indicatorchartoption",
            name="symbol",
            field=models.CharField(
                blank=True,
                choices=[
                    ("circle", "circle"),
                    ("square", "square"),
                    ("diamond", "diamond"),
                    ("triangle", "triangle"),
                    ("triangle-down", "triangle-down"),
                ],
                default=None,
                help_text="https://api.highcharts.com/highcharts/plotOptions.spline.marker.symbol",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="breakdownchartoption",
            name="custom_symbol",
            field=models.ImageField(
                blank=True,
                default=None,
                help_text="Custom symbol used instead of the predefined ones",
                null=True,
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="indicatorchartoption",
            name="custom_symbol",
            field=models.ImageField(
                blank=True,
                default=None,
                help_text="Custom symbol used instead of the predefined ones",
                null=True,
                upload_to="",
            ),
        ),
    ]
