# Generated by Django 4.2.3 on 2023-09-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("charts", "0014_breakdownchartoption_symbol_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chart",
            name="legend_layout",
            field=models.CharField(
                blank=True,
                choices=[("horizontal", "horizontal"), ("vertical", "vertical")],
                default=None,
                help_text="Choose default legend layout type",
                max_length=20,
                null=True,
            ),
        ),
    ]
