# Generated by Django 4.2.3 on 2023-09-28 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_alter_period_date"),
        ("charts", "0015_chart_legend_layout"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtraChartNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "note",
                    models.CharField(
                        help_text="Extra notes to show in the chart", max_length=255
                    ),
                ),
                (
                    "indicator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra_notes",
                        to="core.indicator",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.period"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
