# Generated by Django 4.2.10 on 2024-02-13 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("charts", "0017_alter_breakdownchartoption_color_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChartFilterOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(db_index=True, default=100000),
                ),
                (
                    "filter_field",
                    models.CharField(
                        choices=[
                            ("indicatorGroup", "Indicator Group"),
                            ("indicator", "Indicator"),
                            ("breakdownGroup", "Breakdown Group"),
                            ("breakdown", "Breakdown"),
                            ("period", "Period"),
                            ("unit", "Unit"),
                            ("country", "Country"),
                        ],
                        help_text="Order of the filter in the chart. Filters not specified here will use the default order. Filters that are not used in the chart will be ignored.",
                        max_length=50,
                    ),
                ),
                (
                    "chart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filter_order",
                        to="charts.chart",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order"],
                "unique_together": {("chart", "filter_field")},
            },
        ),
    ]
