# Generated by Django 4.2.10 on 2024-02-14 12:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charts", "0018_chartfilterorder"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chartfilterorder",
            options={
                "ordering": ["display_order"],
                "verbose_name": "Chart Filter Order",
                "verbose_name_plural": "Chart Filters Order",
            },
        ),
        migrations.AddField(
            model_name="chart",
            name="max_year",
            field=models.PositiveIntegerField(
                blank=True,
                default=None,
                help_text="Maximum year of the axis. Used for all axes that display dates.This can be vertical, horizontal, or both depending on the chart type.",
                null=True,
                validators=[django.core.validators.MinValueValidator(1990)],
            ),
        ),
        migrations.AddField(
            model_name="chart",
            name="min_year",
            field=models.PositiveIntegerField(
                blank=True,
                default=None,
                help_text="Minimum year of the axis. Used for all axes that display dates.This can be vertical, horizontal, or both depending on the chart type.",
                null=True,
                validators=[django.core.validators.MinValueValidator(1990)],
            ),
        ),
        migrations.AlterField(
            model_name="chart",
            name="max_value",
            field=models.FloatField(
                blank=True,
                default=None,
                help_text="Maximum value of the axis. Used for all axes that display fact values.This can be vertical, horizontal, or both depending on the chart type.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="chart",
            name="min_value",
            field=models.FloatField(
                blank=True,
                default=None,
                help_text="Minimum value of the axis. Used for all axes that display fact values.This can be vertical, horizontal, or both depending on the chart type.",
                null=True,
            ),
        ),
    ]
