# Generated by Django 4.2.10 on 2024-02-20 11:59

import colorfield.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("charts", "0019_alter_chartfilterorder_options_chart_max_year_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChartFontStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field",
                    models.CharField(
                        choices=[
                            ("title.style", "Title"),
                            ("subtitle.style", "Subtitle"),
                            ("legend.itemStyle", "Legend Item"),
                            ("tooltip.style", "Tooltip"),
                            ("xAxis.title.style", "Horizontal Axis Title"),
                            ("yAxis.title.style", "Vertical Axis Title"),
                            ("xAxis.labels.style", "Horizontal Axis Labels"),
                            ("yAxis.labels.style", "Vertical Axis Labels"),
                            ("plotOptions.series.dataLabels.style", "Data Labels"),
                            ("credits.style", "Chart Credits"),
                        ],
                        help_text="The chart item(s) this style applies to.",
                        max_length=60,
                    ),
                ),
                (
                    "font_weight",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (100, "Thin (Hairline)"),
                            (200, "Extra Light (Ultra Light)"),
                            (300, "Light"),
                            (400, "Normal (Regular)"),
                            (500, "Medium"),
                            (600, "Semi Bold (Demi Bold)"),
                            (700, "Bold"),
                            (800, "Extra Bold (Ultra Bold)"),
                            (900, "Black (Heavy)"),
                            (950, "Extra Black (Ultra Black)"),
                        ],
                        default=None,
                        help_text="Set the weight (or boldness) of the font.",
                        null=True,
                    ),
                ),
                (
                    "font_size_px",
                    models.PositiveIntegerField(
                        blank=True,
                        default=None,
                        help_text="Set the font size in pixels.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(8),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "font_color",
                    colorfield.fields.ColorField(
                        blank=True,
                        default=None,
                        help_text="Set the text color.",
                        image_field=None,
                        max_length=25,
                        null=True,
                        samples=None,
                    ),
                ),
                (
                    "chart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="font_styles",
                        to="charts.chart",
                    ),
                ),
            ],
            options={
                "unique_together": {("chart", "field")},
            },
        ),
    ]
