# Generated by Django 4.2.10 on 2024-03-07 10:16

import digital_agenda.apps.charts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("charts", "0020_chartfontstyle"),
    ]

    operations = [
        migrations.AddField(
            model_name="chart",
            name="breakdown_label",
            field=digital_agenda.apps.charts.models.ChartDimensionLabel(
                blank=True,
                choices=[
                    ("label", "Long (label)"),
                    ("alt_label", "Short (alt_label)"),
                    ("code", "Code (code)"),
                ],
                default=None,
                help_text="Label type used while displaying this dimension in the chart. If empty the other labels are used instead.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="chart",
            name="country_label",
            field=digital_agenda.apps.charts.models.ChartDimensionLabel(
                blank=True,
                choices=[
                    ("label", "Long (label)"),
                    ("alt_label", "Short (alt_label)"),
                    ("code", "Code (code)"),
                ],
                default=None,
                help_text="Label type used while displaying this dimension in the chart. If empty the other labels are used instead.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="chart",
            name="indicator_label",
            field=digital_agenda.apps.charts.models.ChartDimensionLabel(
                blank=True,
                choices=[
                    ("label", "Long (label)"),
                    ("alt_label", "Short (alt_label)"),
                    ("code", "Code (code)"),
                ],
                default=None,
                help_text="Label type used while displaying this dimension in the chart. If empty the other labels are used instead.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="chart",
            name="period_label",
            field=digital_agenda.apps.charts.models.ChartDimensionLabel(
                blank=True,
                choices=[
                    ("label", "Long (label)"),
                    ("alt_label", "Short (alt_label)"),
                    ("code", "Code (code)"),
                ],
                default=None,
                help_text="Label type used while displaying this dimension in the chart. If empty the other labels are used instead.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="chart",
            name="unit_label",
            field=digital_agenda.apps.charts.models.ChartDimensionLabel(
                blank=True,
                choices=[
                    ("label", "Long (label)"),
                    ("alt_label", "Short (alt_label)"),
                    ("code", "Code (code)"),
                ],
                default=None,
                help_text="Label type used while displaying this dimension in the chart. If empty the other labels are used instead.",
                max_length=50,
                null=True,
            ),
        ),
    ]
