# Generated by Django 4.2.10 on 2024-03-01 08:29

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ("charts", "0020_chartfontstyle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chart",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name="chartgroup",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name="chartgroup",
            name="license",
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
