# Generated by Django 4.2.10 on 2024-03-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charts", "0021_chart_breakdown_label_chart_country_label_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chart",
            name="use_period_label_for_axis",
            field=models.BooleanField(
                default=False,
                help_text="Use the period labels for date axis instead of the actual dates.",
            ),
        ),
    ]
