# Generated by Django 4.2.10 on 2024-03-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charts", "0022_chart_use_period_label_for_axis"),
    ]

    operations = [
        migrations.AddField(
            model_name="extrachartnote",
            name="hide_from_line_charts",
            field=models.BooleanField(
                default=False,
                help_text="Hide all data points matching this indicator/period combination from all line charts.",
            ),
        ),
    ]
