name: "Continuous Integration"

# Ensure that only one job works on this at a time
concurrency: ci-deploy

on:
  push:
    branches:
      - 'master'

jobs:
  docker-build:
    uses: ./.github/workflows/docker-build.yml
  deploy-test:
    needs: docker-build
    uses: ./.github/workflows/deploy.yml
    with:
      deployEnvironment: desi-test
      workingDir: /var/local/desi/
