name: "Continuous Integration"

on:
  push:
    branches:
      - 'master'

jobs:
  docker-build:
    uses: ./.github/workflows/docker-build.yml
  deploy-staging:
    needs: docker-build
    uses: ./.github/workflows/deploy-staging.yml
