name: Deploy
permissions:
  contents: read

on:
  workflow_call:
    inputs:
      deployEnvironment:
        description: 'Deploy environment (e.g. desi-test, desi-prod)'
        required: true
        type: string
      workingDir:
        description: 'Working dir'
        required: true
        default: '/var/local/desi/'
        type: string

jobs:
  deploy:
    runs-on:
      - self-hosted
      - ${{ inputs.deployEnvironment }}
    steps:
      - uses: actions/checkout@v4
      - name: Update docker-compose.yml
        run: |
          cp docker-compose.yml "${{ inputs.workingDir }}"
      - name: Update services
        run: |
          cd "${{ inputs.workingDir }}"
          sed -i "/^DOCKER_TAG=/c\DOCKER_TAG=$GITHUB_REF_NAME" .env
          docker compose pull
          docker compose up -d --remove-orphans
          docker compose top


