name: Deploy Staging

# Ensure that only one job works on this at a time
concurrency: staging_deployment

on:
  # Run after new images are deployed
  workflow_run:
    workflows: ["Create and publish a Docker images"]
    types:
      - completed
    branches:
      - master

jobs:
  deploy:
    runs-on:
      - self-hosted
      - digital-agenda-staging
    steps:
      - uses: actions/checkout@v3
      - name: Update docker-compose.yml
        run: |
          cp docker-compose.yml /home/digital-agenda/
      - name: Update services
        run: |
          cd /home/digital-agenda/
          sed -i "/^DOCKER_TAG=/c\DOCKER_TAG=$GITHUB_REF_NAME" .env
          docker compose pull
          docker compose up -d
          docker compose top

