name: "Check Backend Code Style"
permissions:
  contents: read

on:
  workflow_call:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: "Install black"
        run: |
          pip install -c requirements/constraints.txt black
      - name: "Lint backend code"
        run: |
          black --extend-exclude=migrations --check digital_agenda/