name: "Code Style"

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  lint-backend:
    uses: ./.github/workflows/lint-backend.yml
  lint-frontend:
    uses: ./.github/workflows/lint-frontend.yml
